### ISSUE TITLE
Podcast episodes aren't properly linked to

### ISSUE THREAD

**Issue by matija-p9** [Dvadeset-Jedan/dvadesetjedan.com#2]
The podcast page is rendered correctly, and data from Anchor.fm is fetched as well.
However, there's a problem with the references on the podcast page.

![podcast linking](https://user-images.githubusercontent.com/59355738/169637691-ea1c3fd8-8526-4aad-a2c7-7b707cbb6dec.png)

Locally thrown error points to an obvious source, but I couldn't solve it:

```
TypeError: src\includes\mixins.pug:80
    78| mixin episodePlayer(e)
    79|   .player.player--single&attributes(attributes)
  > 80|     a.player__coverlink(href=`/podcast/${e.slug}/`)
    81|       img.player__cover(src=imgLarge data-amplitude-song-info="cover_art_url" data-amplitude-main-song-info="true")
    82|     .player__bottom
    83|       progress.player__progress.amplitude-song-played-progress(data-amplitude-main-song-played-progress="true")

Cannot read properties of undefined (reading 'slug')
    at Object.pug_interp [as episodePlayer] (eval at wrap (C:\_INTERLINK\einundzwanzig.space\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:250:98)
    at eval (eval at wrap (C:\_INTERLINK\einundzwanzig.space\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:669:28)
    at template (eval at wrap (C:\_INTERLINK\einundzwanzig.space\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:750:7)
    at Object.exports.renderFile (C:\_INTERLINK\einundzwanzig.space\node_modules\pug\lib\index.js:454:38)
    at renderPage (C:\_INTERLINK\einundzwanzig.space\tasks\generate_pages.js:19:24)
    at Object.<anonymous> (C:\_INTERLINK\einundzwanzig.space\tasks\generate_pages.js:52:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  path: 'src\\includes\\mixins.pug'
}
```

**Comment by matija-p9** [comment]
Files changed for this objective (there's probably a better way):

src\episode.pug
-line 11, it's possible the content needs to reference dvadesetjedan.com. It didn't work for me when it referenced my localhost

src\includes\mixins.pug
- line 12, replaced verschiedenes and Verschiedenes with kategorija and Kategorija
- line 118, replaced Einundzwanzig with Dvadesetjedan

tasks\fetch_feed.js
- line 47, replaced Verschiedenes with Kategorija
- line 56, replaced verschiedenes with kategorija

tasks\generate_pages.js
- line 56, replaced verschiedenes with kategorija
